# Generated by Django 3.2.5 on 2021-09-09 11:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('groomings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 9, 9, 11, 1, 20, 868771, tzinfo=utc))),
                ('text', models.TextField(blank=True, null=True)),
                ('favorite', models.ManyToManyField(related_name='user_favo_post', to='groomings.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to='groomings.user')),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 9, 9, 11, 1, 20, 868771, tzinfo=utc))),
                ('text', models.TextField()),
                ('favorite', models.ManyToManyField(related_name='user_favo_comme', to='groomings.User')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groomings.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='groomings.user')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
