# Generated by Django 3.2.5 on 2021-10-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groomings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.FileField(null=True, upload_to='question_image/'),
        ),
        migrations.AddField(
            model_name='reply',
            name='image',
            field=models.FileField(null=True, upload_to='reply_image/'),
        ),
    ]
