# Generated by Django 3.2.5 on 2021-11-10 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groomings', '0003_user_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='bad',
            field=models.ManyToManyField(related_name='user_bad', to=settings.AUTH_USER_MODEL),
        ),
    ]
