# Generated by Django 3.2.5 on 2021-11-16 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groomings', '0004_comment_bad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='good_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='good_question',
        ),
        migrations.AddField(
            model_name='question',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='to_giver_point',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='question',
            name='to_recipient_point',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
