# Generated by Django 3.2.5 on 2021-09-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groomings', '0004_give_point_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='カテゴリーなし', max_length=15),
        ),
    ]
