# Generated by Django 3.2.5 on 2021-11-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groomings', '0005_auto_20211116_2209'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('post', models.ManyToManyField(related_name='having_tags', to='groomings.Post')),
            ],
            options={
                'db_table': 'tag',
            },
        ),
    ]
