# Generated by Django 3.2.5 on 2021-09-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groomings', '0005_category_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterModelTable(
            name='reply',
            table='reply',
        ),
    ]
