# Generated by Django 3.2.5 on 2021-09-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groomings', '0006_title_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='good_answer',
            field=models.ManyToManyField(related_name='user_good_answer', to='groomings.User'),
        ),
        migrations.AddField(
            model_name='question',
            name='good_question',
            field=models.ManyToManyField(related_name='user_good_question', to='groomings.User'),
        ),
    ]
