# Generated by Django 3.2.5 on 2021-11-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groomings', '0006_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='image',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='is_activate',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.FileField(null=True, upload_to='post_image/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image3',
            field=models.FileField(null=True, upload_to='post_image/'),
        ),
        migrations.AddField(
            model_name='question',
            name='image2',
            field=models.FileField(null=True, upload_to='question_image/'),
        ),
        migrations.AddField(
            model_name='question',
            name='image3',
            field=models.FileField(null=True, upload_to='question_image/'),
        ),
    ]
