# Generated by Django 3.2.5 on 2021-11-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groomings', '0007_auto_20211122_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(null=True, upload_to='user_image/'),
        ),
    ]
