# Generated by Django 3.2.5 on 2021-09-13 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groomings', '0008_comment_user_related_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_reply', to='groomings.question'),
        ),
    ]
