# Generated by Django 3.2.5 on 2021-11-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groomings', '0008_user_image_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to='post_image/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='post_image/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to='post_image/'),
        ),
    ]
