# Generated by Django 3.2.5 on 2021-10-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groomings', '0009_reply_question_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(null=True, upload_to='post_image/'),
        ),
    ]
