# Generated by Django 3.2.5 on 2021-11-24 06:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groomings', '0011_alter_post_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Togiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Torecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to='question_image/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='question_image/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to='question_image/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='user_image/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='to_giver_point',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gp_question', to='groomings.togiver'),
        ),
        migrations.AlterField(
            model_name='question',
            name='to_recipient_point',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rp_question', to='groomings.torecipient'),
        ),
    ]
