# Generated by Django 3.2.5 on 2021-11-24 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groomings', '0013_notify'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notify',
            table='notify',
        ),
    ]
