# Generated by Django 3.2.5 on 2021-11-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groomings', '0014_alter_notify_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='is_visited',
            field=models.BooleanField(default=False),
        ),
    ]
