# Generated by Django 3.2.5 on 2021-11-25 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groomings', '0015_notify_is_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='to_giver_point',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groomings.togiver'),
        ),
        migrations.AlterField(
            model_name='question',
            name='to_recipient_point',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groomings.torecipient'),
        ),
    ]
