# Generated by Django 3.2.5 on 2021-11-25 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groomings', '0016_auto_20211125_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='to_giver_point',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='to_recipient_point',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.DeleteModel(
            name='Togiver',
        ),
        migrations.DeleteModel(
            name='Torecipient',
        ),
    ]
