# Generated by Django 3.2.5 on 2021-11-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groomings', '0017_auto_20211125_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
