# Generated by Django 3.2.5 on 2021-12-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groomings', '0018_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
